// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_message.proto

package gRPC.demo;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gRPC.demo.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
